TRUNCATE TABLE 
	line_items,
	orders,
	users,
	products,
	categories,
	carts RESTART IDENTITY;

INSERT INTO carts (UUID, created_at, updated_at)
VALUES
	('a6b14dc5-8102-4d14-8d43-73bf16118eec', now(), now()),
	('8f3a2cd3-3fc5-42e3-8ca8-c235e034e3a8', now(), now()),
	('f0629416-fa41-4850-b598-db7b1908a483', now(), now());

INSERT INTO categories (name, created_at, updated_at)
VALUES
	('tops', now(), now()),
	('bottoms', now(), now()),
	('accessories', now(), now());

INSERT INTO products (base_sku, sku, name, category, description, gender, photo_url, created_at, updated_at, price_cents, size, color, quantity_available)
VALUES
	-- product placeholder image: https://i.imgur.com/Gn9PPb3.png

	-- all over print shirts
	('AOP-Tee', 'AOP-Tee-XS-BLUE', 'All Over Print T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'blue', 3),
	('AOP-Tee', 'AOP-Tee-S-BLUE', 'All Over Print T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'blue', 3),
	('AOP-Tee', 'AOP-Tee-M-BLUE', 'All Over Print T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'blue', 3),
	('AOP-Tee', 'AOP-Tee-L-BLUE', 'All Over Print T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'blue', 3),
	('AOP-Tee', 'AOP-Tee-XL-BLUE', 'All Over Print T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'blue', 3),

	-- american tour collection
	('ATC-OK-Beanie', 'ATC-OK-Beanie-M-WHITE', 'Oklahoma Beanie', 'accessories', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615644/MyStripesProducts/American%20Tour%20Collection/Beanies/Oklahoma_Beanie_1_rmnlfi.png', now(), now(), 2200, 'M', 'white', 0),
	('ATC-OK-DadHat', 'ATC-OK-DadHat-M-WHITE', 'Oklahoma Dad Hat', 'accessories', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615642/MyStripesProducts/American%20Tour%20Collection/Hats/Oklahoma_Dad_Hat_bie9vy.png', now(), now(), 2200, 'M', 'white', 2),
	
	('ATC-OK-Hoodie', 'ATC-OK-Hoodie-XS-WHITE', 'Oklahoma Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615666/MyStripesProducts/American%20Tour%20Collection/Hoodies/The_American_Tour-_Oklahoma_ghvq3d.png', now(), now(), 3500, 'XS', 'white', 4),
	('ATC-OK-Hoodie', 'ATC-OK-Hoodie-S-WHITE', 'Oklahoma Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615666/MyStripesProducts/American%20Tour%20Collection/Hoodies/The_American_Tour-_Oklahoma_ghvq3d.png', now(), now(), 3500, 'S', 'white', 4),
	('ATC-OK-Hoodie', 'ATC-OK-Hoodie-M-WHITE', 'Oklahoma Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615666/MyStripesProducts/American%20Tour%20Collection/Hoodies/The_American_Tour-_Oklahoma_ghvq3d.png', now(), now(), 3500, 'M', 'white', 4),
	('ATC-OK-Hoodie', 'ATC-OK-Hoodie-L-WHITE', 'Oklahoma Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615666/MyStripesProducts/American%20Tour%20Collection/Hoodies/The_American_Tour-_Oklahoma_ghvq3d.png', now(), now(), 3500, 'L', 'white', 4),
	('ATC-OK-Hoodie', 'ATC-OK-Hoodie-XL-WHITE', 'Oklahoma Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615666/MyStripesProducts/American%20Tour%20Collection/Hoodies/The_American_Tour-_Oklahoma_ghvq3d.png', now(), now(), 3500, 'XL', 'white', 4),
	
	('ATC-OK-Tee', 'ATC-OK-Tee-XS-WHITE', 'Oklahoma T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615641/MyStripesProducts/American%20Tour%20Collection/Tees/The_American_Tour-_T_shirt_Oklahoma_yajzd6.png', now(), now(), 2500, 'XS', 'white', 3),
	('ATC-OK-Tee', 'ATC-OK-Tee-S-WHITE', 'Oklahoma T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615641/MyStripesProducts/American%20Tour%20Collection/Tees/The_American_Tour-_T_shirt_Oklahoma_yajzd6.png', now(), now(), 2500, 'S', 'white', 3),
	('ATC-OK-Tee', 'ATC-OK-Tee-M-WHITE', 'Oklahoma T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615641/MyStripesProducts/American%20Tour%20Collection/Tees/The_American_Tour-_T_shirt_Oklahoma_yajzd6.png', now(), now(), 2500, 'M', 'white', 3),
	('ATC-OK-Tee', 'ATC-OK-Tee-L-WHITE', 'Oklahoma T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615641/MyStripesProducts/American%20Tour%20Collection/Tees/The_American_Tour-_T_shirt_Oklahoma_yajzd6.png', now(), now(), 2500, 'L', 'white', 3),
	('ATC-OK-Tee', 'ATC-OK-Tee-XL-WHITE', 'Oklahoma T-shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615641/MyStripesProducts/American%20Tour%20Collection/Tees/The_American_Tour-_T_shirt_Oklahoma_yajzd6.png', now(), now(), 2500, 'XL', 'white', 3),

	-- bella canvas collection
	  -- hoodies
	('BC-Hoodie', 'BC-Hoodie-XS-GRAY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'gray', 4),
	('BC-Hoodie', 'BC-Hoodie-S-GRAY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'gray', 4),
	('BC-Hoodie', 'BC-Hoodie-M-GRAY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'gray', 4),
	('BC-Hoodie', 'BC-Hoodie-L-GRAY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'gray', 4),
	('BC-Hoodie', 'BC-Hoodie-XL-GRAY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'gray', 4),
	
	('BC-Hoodie', 'BC-Hoodie-XS-NAVY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'navy', 4),
	('BC-Hoodie', 'BC-Hoodie-S-NAVY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'navy', 4),
	('BC-Hoodie', 'BC-Hoodie-M-NAVY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'navy', 4),
	('BC-Hoodie', 'BC-Hoodie-L-NAVY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'navy', 4),
	('BC-Hoodie', 'BC-Hoodie-XL-NAVY', 'Bella Canvas Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'navy', 4),

	  -- tees
	    -- flat color
	('BC-Tee-Flat', 'BC-Tee-Flat-XS-WHITE', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'white', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-WHITE', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'white', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-WHITE', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'white', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-WHITE', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'white', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-WHITE', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'white', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-ROYALBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'royalblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-ROYALBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'royalblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-ROYALBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'royalblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-ROYALBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'royalblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-ROYALBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'royalblue', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-STEELBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'steelblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-STEELBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'steelblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-STEELBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'steelblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-STEELBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'steelblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-STEELBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'steelblue', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-OCEANBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'skyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-OCEANBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'skyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-OCEANBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'skyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-OCEANBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'skyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-OCEANBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'skyblue', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-AQUABL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'deepskyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-AQUABL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'deepskyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-AQUABL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'deepskyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-AQUABL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'deepskyblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-AQUABL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'deepskyblue', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-LIGHTBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'lightblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-LIGHTBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'lightblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-LIGHTBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'lightblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-LIGHTBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'lightblue', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-LIGHTBL', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'lightblue', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-FORESTGR', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'darkolivegreen', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-FORESTGR', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'darkolivegreen', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-FORESTGR', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'darkolivegreen', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-FORESTGR', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'darkolivegreen', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-FORESTGR', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'darkolivegreen', 4),
	
	('BC-Tee-Flat', 'BC-Tee-Flat-XS-ASPHALT', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'dimgray', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-ASPHALT', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'dimgray', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-ASPHALT', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'dimgray', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-ASPHALT', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'dimgray', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-ASPHALT', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'dimgray', 4),

	('BC-Tee-Flat', 'BC-Tee-Flat-XS-ARMY', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'darkkhaki', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-S-ARMY', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'darkkhaki', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-M-ARMY', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'darkkhaki', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-L-ARMY', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'darkkhaki', 4),
	('BC-Tee-Flat', 'BC-Tee-Flat-XL-ARMY', 'Bella Canvas Flat T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'darkkhaki', 4),
		-- heather color
	('BC-Tee-Heather', 'BC-Tee-Heather-XS-ROYALBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'royalblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-S-ROYALBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'royalblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-M-ROYALBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'royalblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-L-ROYALBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'royalblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-XL-ROYALBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'royalblue', 4),

	('BC-Tee-Heather', 'BC-Tee-Heather-XS-FORESTGR', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'darkolivegreen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-S-FORESTGR', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'darkolivegreen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-M-FORESTGR', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'darkolivegreen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-L-FORESTGR', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'darkolivegreen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-XL-FORESTGR', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'darkolivegreen', 4),

	('BC-Tee-Heather', 'BC-Tee-Heather-XS-LIGHTBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'lightblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-S-LIGHTBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'lightblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-M-LIGHTBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'lightblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-L-LIGHTBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'lightblue', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-XL-LIGHTBL', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'lightblue', 4),

	('BC-Tee-Heather', 'BC-Tee-Heather-XS-DARKGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'darkslategray', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-S-DARKGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'darkslategray', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-M-DARKGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'darkslategray', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-L-DARKGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'darkslategray', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-XL-DARKGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'darkslategray', 4),

	('BC-Tee-Heather', 'BC-Tee-Heather-XS-LIGHTGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'gainsboro', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-S-LIGHTGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'gainsboro', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-M-LIGHTGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'gainsboro', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-L-LIGHTGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'gainsboro', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-XL-LIGHTGRAY', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'gainsboro', 4),
	
	('BC-Tee-Heather', 'BC-Tee-Heather-XS-ASH', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XS', 'linen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-S-ASH', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'S', 'linen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-M-ASH', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'M', 'linen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-L-ASH', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'L', 'linen', 4),
	('BC-Tee-Heather', 'BC-Tee-Heather-XL-ASH', 'Bella Canvas Heather T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 2500, 'XL', 'linen', 4),

	-- my stripes custom merch collection
	('MSCM-Beanie', 'MSCM-Beanie-XS', 'My Stripes Beanie', 'accessories', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615689/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Beanie_rqxc8m.png', now(), now(), 2200, 'M', 'white', 0),
	('MSCM-DadHat', 'MSCM-DadHat-M-WHITE', 'My Stripes Dad Hat', 'accessories', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615695/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Dad_Hat_hipah5.png', now(), now(), 2200, 'M', 'white', 5),

	('MSCM-Tee', 'MSCM-Tee-XS-WHITE', 'My Stripes T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_T-shirt_t3r3lf.png', now(), now(), 2500, 'XS', 'white', 4),
	('MSCM-Tee', 'MSCM-Tee-S-WHITE', 'My Stripes T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_T-shirt_t3r3lf.png', now(), now(), 2500, 'S', 'white', 4),
	('MSCM-Tee', 'MSCM-Tee-M-WHITE', 'My Stripes T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_T-shirt_t3r3lf.png', now(), now(), 2500, 'M', 'white', 4),
	('MSCM-Tee', 'MSCM-Tee-L-WHITE', 'My Stripes T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_T-shirt_t3r3lf.png', now(), now(), 2500, 'L', 'white', 4),
	('MSCM-Tee', 'MSCM-Tee-XL-WHITE', 'My Stripes T-Shirt', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'M', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_T-shirt_t3r3lf.png', now(), now(), 2500, 'XL', 'white', 4),

	('MSCM-Hoodie', 'MSCM-Hoodie-XS-WHITE', 'My Stripes Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Custom_Merch_Hoodie_gla8a9.png', now(), now(), 3500, 'XS', 'white', 4),
	('MSCM-Hoodie', 'MSCM-Hoodie-S-WHITE', 'My Stripes Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Custom_Merch_Hoodie_gla8a9.png', now(), now(), 3500, 'S', 'white', 4),
	('MSCM-Hoodie', 'MSCM-Hoodie-M-WHITE', 'My Stripes Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Custom_Merch_Hoodie_gla8a9.png', now(), now(), 3500, 'M', 'white', 4),
	('MSCM-Hoodie', 'MSCM-Hoodie-L-WHITE', 'My Stripes Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Custom_Merch_Hoodie_gla8a9.png', now(), now(), 3500, 'L', 'white', 4),
	('MSCM-Hoodie', 'MSCM-Hoodie-XL-WHITE', 'My Stripes Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615690/MyStripesProducts/My%20Stripes%20Custom%20Merch/My_Stripes_Custom_Merch_Hoodie_gla8a9.png', now(), now(), 3500, 'XL', 'white', 4),

	-- world tour collection
	('WTC-Hoodie', 'WTC-Hoodie-XS-WHITE', 'World Tour - Australia Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615712/MyStripesProducts/World%20Tour%20Collection/Hoodies/World_Tour-_Austrilia_Hoodie_vkd1bz.png', now(), now(), 3500, 'XS', 'white', 4),
	('WTC-Hoodie', 'WTC-Hoodie-S-WHITE', 'World Tour - Australia Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615712/MyStripesProducts/World%20Tour%20Collection/Hoodies/World_Tour-_Austrilia_Hoodie_vkd1bz.png', now(), now(), 3500, 'S', 'white', 4),
	('WTC-Hoodie', 'WTC-Hoodie-M-WHITE', 'World Tour - Australia Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615712/MyStripesProducts/World%20Tour%20Collection/Hoodies/World_Tour-_Austrilia_Hoodie_vkd1bz.png', now(), now(), 3500, 'M', 'white', 4),
	('WTC-Hoodie', 'WTC-Hoodie-L-WHITE', 'World Tour - Australia Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615712/MyStripesProducts/World%20Tour%20Collection/Hoodies/World_Tour-_Austrilia_Hoodie_vkd1bz.png', now(), now(), 3500, 'L', 'white', 4),
	('WTC-Hoodie', 'WTC-Hoodie-XL-WHITE', 'World Tour - Australia Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://res.cloudinary.com/dswxhdeob/image/upload/v1581615712/MyStripesProducts/World%20Tour%20Collection/Hoodies/World_Tour-_Austrilia_Hoodie_vkd1bz.png', now(), now(), 3500, 'XL', 'white', 4),

	-- champion hoodies
	  -- king champion hoodies
	('Champ-Hoodie-King', 'Champ-Hoodie-King-XS-BLACK', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'black', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-S-BLACK', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'black', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-M-BLACK', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'black', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-L-BLACK', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'black', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-XL-BLACK', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'black', 4),

	('Champ-Hoodie-King', 'Champ-Hoodie-King-XS-GRAY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'lightgray', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-S-GRAY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'lightgray', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-M-GRAY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'lightgray', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-L-GRAY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'lightgray', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-XL-GRAY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'lightgray', 4),

	('Champ-Hoodie-King', 'Champ-Hoodie-King-XS-NAVY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'midnightblue', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-S-NAVY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'midnightblue', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-M-NAVY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'midnightblue', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-L-NAVY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'midnightblue', 4),
	('Champ-Hoodie-King', 'Champ-Hoodie-King-XL-NAVY', 'King Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'midnightblue', 4),
	  -- mystripes champion hoodies
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-XS-BLACK', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'black', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-S-BLACK', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'black', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-M-BLACK', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'black', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-L-BLACK', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'black', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-XL-BLACK', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'black', 4),

	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-XS-GRAY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'lightgray', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-S-GRAY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'lightgray', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-M-GRAY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'lightgray', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-L-GRAY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'lightgray', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-XL-GRAY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'lightgray', 4),

	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-XS-NAVY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XS', 'midnightblue', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-S-NAVY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'S', 'midnightblue', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-M-NAVY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'M', 'midnightblue', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-L-NAVY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'L', 'midnightblue', 4),
	('Champ-Hoodie-MyStripes', 'Champ-Hoodie-MyStripes-XL-NAVY', 'My Stripes Champion Hoodie', 'tops', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 'U', 'https://i.imgur.com/Gn9PPb3.png', now(), now(), 3500, 'XL', 'midnightblue', 4);

INSERT INTO users (email, encrypted_password, admin)
VALUES
	-- admin password is admin123
	('admin@mystripes.com', '$2a$10$ZYFRU.Gg/.e1G7cRJKNcueWH.M4TyRov9LTLV5uGxbhyQSLBK/RtS', TRUE),
	('user@test.com', '$2a$10$hU98gp5TgV65aHgylvurcOZwMjsZspfhCsZdNYEWKXN6kF0bCSdfC', FALSE),
	('demo@email.com', '$2a$10$3TFONhx44jc5xeEb23PmVOuq7LtQsNsLy1Rthjomspza02eJr94SS', FALSE);

INSERT INTO orders (email, address, state, product_skus_and_quantity, amount_cents, UUID)
VALUES
	('user@test.com', '123 Address Lane', 'OK', '{{ATC-OK-Beanie-S-GREEN, 1}, {ATC-OK-Beanie-M-DKBL, 3}, {ATC-OK-DadHat-XS, 5}}', 7900, 'a6b14dc5-8102-4d14-8d43-73bf16118eec'),
	('demo@email.com', '123 Address Lane', 'MN', '{{ATC-OK-DadHat-XS, 3}, {MSCM-Hoodie-XS, 4}, {ATC-OK-Tee-XS, 5}}', 8200, '8f3a2cd3-3fc5-42e3-8ca8-c235e034e3a8');

INSERT INTO line_items (quantity, product_sku, cart_id)
VALUES
	(2, 'ATC-OK-Beanie-M-WHITE', 'a6b14dc5-8102-4d14-8d43-73bf16118eec'),
	(2, 'ATC-OK-DadHat-M-WHITE', 'a6b14dc5-8102-4d14-8d43-73bf16118eec'),
	(1, 'MSCM-Hoodie-XS-WHITE', '8f3a2cd3-3fc5-42e3-8ca8-c235e034e3a8');
